version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: eval-postgres
    environment:
      POSTGRES_USER: evaluser
      POSTGRES_PASSWORD: evalpass
      POSTGRES_DB: evaldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U evaluser"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: eval-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@eval.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
